### ISSUE TITLE
nacao_v2方案失效

### ISSUE THREAD

**Issue by forever139** [9468305/script#1]
新版官网加了验证码，官方app也抓不了包，应该是在客户端写死了认证的证书，中间人抓包都看不了。

**Comment by 9468305** [comment]
官网确实增加了带干扰的英文字母验证码。
是时候祭出大杀器了，建议搜索“远程打码”，提供几个关键字供参考。
`火车头，数多多，打码兔，优优云，营销神器，石像。`
nacao_v2目前不更新验证码破解了，我个人暂时没这个需求，以及验证码识别应该是独立项目和技术专题。
谢谢。
